### ISSUE TITLE
Typescript failing with `graphql` handlers

### ISSUE THREAD

**Issue by andrewmartin** [mswjs/http-middleware#36] opened 2023-11-15 20:53 UTC
Hi there, am working on implementing with the recent `msw2` updates and wanted to ask if this has been seen before:

```ts
import { HttpResponse, RequestHandler, graphql } from 'msw'
import { createServer } from '@mswjs/http-middleware'

export const handlers: RequestHandler[] = [
  graphql.query('ListPosts', () => {
    return HttpResponse.json({
      data: {
        // Convert all posts to an array
        // and return as the "posts" root-level property.
        posts: [{ test: true }],
      },
    })
  }),
]
const httpServer = createServer(...handlers)

console.log('server listening on 9090')
httpServer.listen(9090)
```

![Image 2023-11-15 at 12 51 00 PM](https://github.com/mswjs/http-middleware/assets/273842/180acd41-10c6-4557-bbf1-18980e34b9f9)

I am seeing some failing types here where the `createServer` expects some type `HttpHandler`. 

Ironically, everything works fine when I cast `as any`, just curious if this is expected or a bad pattern.

**Comment by kettanaito** [comment] 2023-11-16 18:02
Oh, there also seems to be a bug right here:

https://github.com/mswjs/http-middleware/blob/50d95e97a30efb453f186751e80bdb393531c0d7/src/server.ts#L5

We annotate the accepted handlers argument as `HttpHandler` only but it should be `RequestHandler`. That's the root case of this. 

@andrewmartin, would you like to open a pull request with a fix? We could get it merged this week then.

**Comment by andrewmartin** [comment] 2023-11-16 19:20
So, the issue is actually with allowing both types of handlers in I believe, shouldn't be harmful for me to annotate. I'd prefer to annotate alongside the `const` declaration so the failing type is caught earlier in the tree.

```ts
src/api/msw/runner.ts:23:33 - error TS2345: Argument of type 'GraphQLHandler[]' is not assignable to parameter of type 'HttpHandler'.
  Type 'GraphQLHandler[]' is missing the following properties from type 'HttpHandler': checkRedundantQueryParameters, parse, predicate, matchMethod, and 9 more.

23 const httpServer = createServer(handlers)
                                   ~~~~~~~~
```

Let me look into opening a fix, but want to clarify the fix just so you're aware. Sorry, should've included that example in my first pass.

**Comment by underfisk** [comment] 2024-01-08 17:20
I can confirm that @andrewmartin issue happens to me when attempting to migrate from v1 to v2, being an inline server using `graphql.mutation` or passing a list of handlers, the type seems to be mismatched

**Comment by saqibakajack** [comment] 2024-03-08 18:52
Hey guys, has anyone managed to resolve this problem?

**Comment by kettanaito** [comment] 2024-03-27 19:10
Can someone please confirm if this issue is reproducible anymore?

We should allow any handler types since `RequestHandler` is the base type for both http and graphql handlers:

https://github.com/mswjs/http-middleware/blob/dfd8c682696f47f3242c6f5a33ab9077a656c5b5/src/middleware.ts#L14

There's also been a lot of work done around the types in v2 so I strongly encourage everyone to upgrade (it is the required MSW version to use this package anyway). If you encounter any issues, please report them, including a reproduction repository. Thanks.

**Closed by kettanaito** 2024-03-27 19:10 UTC
